services:
  amnezia-web-panel:
    image: vikbaranov/amnezia-web-panel:1.1.0
    container_name: amnezia_panel
    volumes:
      - ./data:/app/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "python3 -c \"import socket; s=socket.socket(); s.connect(('localhost', 5000)); s.close()\""]
      interval: 5s
      timeout: 10s
      retries: 3
      start_period: 10s
  caddy:
    image: caddy:2-alpine
    container_name: amnezia-caddy
    restart: unless-stopped
    depends_on:
      - amnezia-web-panel
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - ./caddy-data:/data
      - ./caddy-config:/config
